#!/usr/bin/env python3.13

from pathlib import Path as FSPath
from node import fs_path_to_node
import sys

def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: are-same-node <fs_path1> <fs_path2>", file=sys.stderr)
        sys.exit(1)
    
    try:
        fs_path1 = FSPath(sys.argv[1])
        fs_path2 = FSPath(sys.argv[2])
        
        node1 = fs_path_to_node(fs_path1)
        node2 = fs_path_to_node(fs_path2)
        
        if node1 == node2:
            print("yes")
            sys.exit(0)
        else:
            print("no")
            sys.exit(0)
            
    except ValueError as e:
        print(f"Error: {str(e)}", file=sys.stderr)
        sys.exit(2)
    except OSError as e:
        print(f"File system error: {str(e)}", file=sys.stderr)
        sys.exit(3)

if __name__ == "__main__":
    main()